//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public System.Guid AssignmentsId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public Nullable<System.Guid> SucursalId { get; set; }
        public Nullable<System.Guid> SaleBoxId { get; set; }
        public string UserRecordCreation { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public string RecordStatus { get; set; }
    }
}
