//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Sucursals = new HashSet<Sucursal>();
        }
    
        public System.Guid CompanyId { get; set; }
        public string BusinessName { get; set; }
        public string TradeName { get; set; }
        public string NumberDocument { get; set; }
        public string CellPhone { get; set; }
        public string OptionalCellPhone { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public string Province { get; set; }
        public string District { get; set; }
        public string Slogan { get; set; }
        public byte[] ImageCompany { get; set; }
        public string ProofFooter { get; set; }
        public string GoogleMapsApi { get; set; }
        public string ReniecApi { get; set; }
        public string EmailMailShipping { get; set; }
        public string PasswordMailShipping { get; set; }
        public string HostMailShipping { get; set; }
        public string PortMailShipping { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sucursal> Sucursals { get; set; }
    }
}
