//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.CustomerAddresses = new HashSet<CustomerAddress>();
        }
    
        public System.Guid CustomerId { get; set; }
        public string CodeCustomer { get; set; }
        public string PersonType { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string BusinessName { get; set; }
        public string LastName { get; set; }
        public string Names { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string CellPhone { get; set; }
        public string OptionalCellPhone { get; set; }
        public string Email { get; set; }
        public string CustomerStatus { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerAddress> CustomerAddresses { get; set; }
    }
}
