//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallationRequest()
        {
            this.InstallationRequestCosts = new HashSet<InstallationRequestCost>();
            this.InstallationRequestPlans = new HashSet<InstallationRequestPlan>();
            this.PaymentSchedules = new HashSet<PaymentSchedule>();
            this.InstallationRequestAttendeds = new HashSet<InstallationRequestAttended>();
        }
    
        public System.Guid InstallationRequestId { get; set; }
        public System.Guid CustomerAddressId { get; set; }
        public Nullable<System.Guid> EmployeeId { get; set; }
        public string ServiceStatus { get; set; }
        public int PayDay { get; set; }
        public int CreateInvoices { get; set; }
        public int DaysOfGrace { get; set; }
        public bool ApplyDiscount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<int> DiscountMonths { get; set; }
        public Nullable<System.DateTime> DateAttention { get; set; }
        public string HourAttention { get; set; }
        public Nullable<System.Guid> TechnicalId { get; set; }
        public string Comment { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestCost> InstallationRequestCosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestPlan> InstallationRequestPlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentSchedule> PaymentSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestAttended> InstallationRequestAttendeds { get; set; }
    }
}
