//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationRequestProgramming
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallationRequestProgramming()
        {
            this.InstallationRequestProgrammingLogs = new HashSet<InstallationRequestProgrammingLog>();
            this.InstallationRequestProgrammingMaterials = new HashSet<InstallationRequestProgrammingMaterial>();
        }
    
        public System.Guid InstallationRequestProgrammingId { get; set; }
        public Nullable<System.Guid> InstallationRequestId { get; set; }
        public Nullable<System.DateTime> DateAttention { get; set; }
        public Nullable<System.TimeSpan> HourAttention { get; set; }
        public Nullable<System.Guid> TechnicalId { get; set; }
        public string Comment { get; set; }
        public string UserRecordCreation { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual InstallationRequest InstallationRequest { get; set; }
        public virtual Technical Technical { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestProgrammingLog> InstallationRequestProgrammingLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestProgrammingMaterial> InstallationRequestProgrammingMaterials { get; set; }
    }
}
