//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationRequestProgrammingLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstallationRequestProgrammingLog()
        {
            this.InstallationRequestProgrammingLogImages = new HashSet<InstallationRequestProgrammingLogImage>();
        }
    
        public System.Guid InstallationRequestProgrammingLogId { get; set; }
        public Nullable<System.Guid> InstallationRequestProgrammingId { get; set; }
        public string InstallationRequestType { get; set; }
        public string Comment { get; set; }
        public string UserRecordCreation { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual InstallationRequestProgramming InstallationRequestProgramming { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstallationRequestProgrammingLogImage> InstallationRequestProgrammingLogImages { get; set; }
    }
}
