//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallationRequestAttended
    {
        public System.Guid InstallationRequestAttendedId { get; set; }
        public System.Guid InstallationRequestId { get; set; }
        public Nullable<System.DateTime> DateAttended { get; set; }
        public string HourAttended { get; set; }
        public Nullable<System.Guid> TechnicalAttendedId { get; set; }
        public string RequestStatus { get; set; }
        public string Comment { get; set; }
        public string Equipment { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Serie { get; set; }
        public string OltPower { get; set; }
        public string CatvPower { get; set; }
        public string Nap { get; set; }
        public string Thread { get; set; }
        public string Route { get; set; }
        public string Trunk { get; set; }
        public string Sector { get; set; }
        public string District { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string TerminalCapacityFirst { get; set; }
        public string TerminalCapacitySecond { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual InstallationRequest InstallationRequest { get; set; }
    }
}
