//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentScheduleDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentScheduleDetail()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public System.Guid PaymentScheduleDetailId { get; set; }
        public System.Guid PaymentScheduleId { get; set; }
        public string VoucherNumber { get; set; }
        public System.DateTime BroadcastDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public decimal PayableAmount { get; set; }
        public decimal PendingAmount { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual PaymentSchedule PaymentSchedule { get; set; }
    }
}
