//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.PaymentFeeSchedules = new HashSet<PaymentFeeSchedule>();
            this.ScheduleDetails = new HashSet<ScheduleDetail>();
        }
    
        public System.Guid ScheduleId { get; set; }
        public Nullable<System.Guid> CustomerAddressId { get; set; }
        public string Account { get; set; }
        public string Customer { get; set; }
        public string DocumentNumber { get; set; }
        public string CellPhone { get; set; }
        public string Zone { get; set; }
        public string Avenue { get; set; }
        public string Address { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> PayPerDay { get; set; }
        public Nullable<int> DaysProration { get; set; }
        public Nullable<int> DaysMonth { get; set; }
        public Nullable<decimal> TotalInstallation { get; set; }
        public Nullable<decimal> TotalPlan { get; set; }
        public Nullable<decimal> TotalMonth { get; set; }
        public Nullable<decimal> TotalOnAccount { get; set; }
        public Nullable<decimal> TotalPending { get; set; }
        public string UserRecordCreation { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual CustomerAddress CustomerAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentFeeSchedule> PaymentFeeSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleDetail> ScheduleDetails { get; set; }
    }
}
