//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleDetail
    {
        public System.Guid ScheduleDetailId { get; set; }
        public Nullable<System.Guid> ScheduleId { get; set; }
        public string Concept { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string UserRecordCreation { get; set; }
        public Nullable<System.DateTime> RecordCreationDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
