//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technical
    {
        public System.Guid TechnicalId { get; set; }
        public string TypeDocument { get; set; }
        public string DocumentNumber { get; set; }
        public string LastName { get; set; }
        public string Names { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public byte[] Password { get; set; }
        public string UserRecordCreation { get; set; }
        public System.DateTime RecordCreationDate { get; set; }
        public string UserEditRecord { get; set; }
        public Nullable<System.DateTime> RecordEditDate { get; set; }
        public string RecordStatus { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
