//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCobradorPorZona
    {
        public System.Guid ManagerZoneId { get; set; }
        public System.Guid ManagerId { get; set; }
        public string Manager { get; set; }
        public System.Guid ZoneId { get; set; }
        public string Zone { get; set; }
        public string RecordStatus { get; set; }
    }
}
