//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vCronogramaPago
    {
        public System.Guid ScheduleId { get; set; }
        public Nullable<System.Guid> CustomerAddressId { get; set; }
        public string Account { get; set; }
        public string Customer { get; set; }
        public string DocumentNumber { get; set; }
        public string CellPhone { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<decimal> TotalPending { get; set; }
    }
}
