//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vGestore
    {
        public System.Guid ManagerId { get; set; }
        public string TypeDocument { get; set; }
        public string TypeDocumentId { get; set; }
        public string DocumentNumber { get; set; }
        public string EmployeeName { get; set; }
        public string LastName { get; set; }
        public string Names { get; set; }
    }
}
