//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSolicitudesInstalacion
    {
        public System.Guid CustomerId { get; set; }
        public System.Guid CustomerAddressId { get; set; }
        public System.Guid InstallationRequestId { get; set; }
        public string DocumentNumber { get; set; }
        public string BusinessName { get; set; }
        public string LastName { get; set; }
        public string Names { get; set; }
        public string CellPhones { get; set; }
        public string ZoneAvenue { get; set; }
        public string AdressDetail { get; set; }
        public string DateAttention { get; set; }
        public string CustomerAddressStatus { get; set; }
    }
}
