//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VipChannel.Domain.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSucursalPorCaja
    {
        public System.Guid SaleBoxId { get; set; }
        public string NameSucursal { get; set; }
        public string NameCaja { get; set; }
    }
}
